Installation Guide
cesium/guides pull request #8
Opened 2023-03-10 10:58 UTC by ruioliveira02

2023-03-10 11:13 UTC, RuiL1904 commented on public/scripts/installation.sh
> +}
This function is repeated twice.

2023-03-10 11:13 UTC, RuiL1904 commented on public/scripts/installation.sh
> +    # Apply the changes so that ASDF in in $PATH
```suggestion
    # Apply the changes so that ASDF is in $PATH
```

2023-03-10 11:13 UTC, RuiL1904 commented on public/scripts/installation.sh
> +    sudo mkdir -m 0755 -p /etc/apt/keyrings
This line of code is repeated twice.

2023-03-10 11:13 UTC, RuiL1904 commented on public/scripts/installation.sh
> +    # Run without sudo
```suggestion
    # In order to run docker command without sudo
```

2023-03-10 11:18 UTC, MarioRodrigues10 requested changes

2023-03-10 11:18 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +### Web Browsers
Please refer [CORS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/)

2023-03-10 11:18 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +
```suggestion
macOS | brew install --cask postman
```

2023-03-10 11:18 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +description: A guide on installing the required software to contribute to CAOS
```suggestion
description: A guide for installing the required software to contribute to CAOS

```

2023-03-10 11:18 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +A guide on installing the required software to contribute to CAOS
```suggestion
A guide for installing the required software to contribute to CAOS

```

2023-03-10 12:21 UTC, tiago-bacelar requested changes
Make the script to work for ZSH. Currently ASDF is only installed for Bash.

2023-03-16 12:13 UTC, tiago-bacelar requested changes

2023-03-16 12:13 UTC, tiago-bacelar commented on src/pages/docs/installation.md
> +| OS | Command |
This table isn't formatted correctly
![image](https://user-images.githubusercontent.com/70779845/225613437-1896687f-5410-4a49-b1b4-d1c837d72d29.png)

2023-03-18 09:55 UTC, MarioRodrigues10 requested changes

2023-03-18 09:55 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +title: CAOS installation guide
```suggestion
title: CeSIUM installation guide
```

2023-03-18 09:55 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +description: A guide to installing the required software to contribute to CAOS
```suggestion
description: A guide to installing the required software to contribute to CeSIUM
```

2023-03-18 09:55 UTC, MarioRodrigues10 commented on src/pages/docs/installation.md
> +A guide to installing the required software to contribute to CAOS
```suggestion
A guide to installing the required software to contribute to CeSIUM
```

2023-03-18 10:05 UTC, MarioRodrigues10 approved these changes

2023-03-18 17:00 UTC, tiago-bacelar approved these changes

2023-03-18 19:23 UTC, merged